apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-controller-manager-operator
  namespace: openshift-kube-controller-manager-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  groups:
    - name: cluster-version
      rules:
        - alert: KubeControllerManagerDown
          annotations:
            summary: Target disappeared from Prometheus target discovery.
            description: KubeControllerManager has disappeared from Prometheus target discovery.
          expr: |
            absent(up{job="kube-controller-manager"} == 1)
          for: 15m
          labels:
            severity: critical
            namespace: openshift-kube-controller-manager
        - alert: PodDisruptionBudgetAtLimit
          annotations:
            summary: The pod disruption budget is preventing further disruption to pods.
            description: The pod disruption budget is at minimum disruptions allowed level. The number of current healthy pods is equal to desired healthy pods.
          expr: |
            max by(namespace, poddisruptionbudget) (kube_poddisruptionbudget_status_current_healthy == kube_poddisruptionbudget_status_desired_healthy and on (namespace, poddisruptionbudget) kube_poddisruptionbudget_status_expected_pods > 0)
          for: 60m
          labels:
            severity: warning
        - alert: PodDisruptionBudgetLimit
          annotations:
            summary: The pod disruption budget registers insufficient amount of pods.
            description: The pod disruption budget is below minimum disruptions allowed level and is not satisfied. The number of current healthy pods is less than then desired healthy pods.
          expr: |
            max by (namespace, poddisruptionbudget) (kube_poddisruptionbudget_status_current_healthy < kube_poddisruptionbudget_status_desired_healthy)
          for: 15m
          labels:
            severity: critical
        - alert: GarbageCollectorSyncFailed
          annotations:
            summary: There was a problem with syncing the resources for garbage collection.
            description: Garbage Collector had a problem with syncing and monitoring the available resources. Please see KubeControllerManager logs for more details.
          expr: |
            rate(garbagecollector_controller_resources_sync_error_total{}[5m]) > 0
          for: 60m
          labels:
            severity: warning
        - alert: GarbageCollectorObjectDeletionFailed
          annotations:
            summary: There was a problem with deleting an object.
            description: Garbage Collector had some problems when attempting to delete an object. Please see KubeControllerManager logs for more details.
          expr: |
            garbagecollector_controller_attempt_to_delete_queue_retry_since_seconds_count - ignoring(le) garbagecollector_controller_attempt_to_delete_queue_retry_since_seconds_bucket{le="100"} > 0
          for: 60m
          labels:
            severity: warning
        - alert: GarbageCollectorObjectOrphaningFailed
          annotations:
            summary: There was a problem with orphaning an object.
            description: Garbage Collector had a problem when attempting to orphan an object. Please see KubeControllerManager logs for more details.
          expr: |
            garbagecollector_controller_attempt_to_orphan_queue_retry_since_seconds_count - ignoring(le) garbagecollector_controller_attempt_to_orphan_queue_retry_since_seconds_bucket{le="100"} > 0
          for: 60m
          labels:
            severity: warning
