apiVersion: v1
kind: Service
metadata:
  namespace: openshift-kube-controller-manager
  name: kube-controller-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: kcm-cpc-reverse-proxy-serving-cert
  labels:
    prometheus: "kube-controller-manager"
spec:
  selector:
    kube-controller-manager: "true"
  ports:
  - name: https
    port: 443
    targetPort: 10257
